### ISSUE TITLE
desmume for ARM builds

### ISSUE THREAD

**Issue by CoalaJoe** [lakkatv/Lakka-LibreELEC#13]

**Comment by Kivutar** [comment]
It would be too slow anyway

**Comment by CoalaJoe** [comment]
Retropie bundles it under experimental. It actually works on my Raspberry Pi 3 better than the N64 emulator bundled with the Raspberry Pi2 Lakka build.

**Comment by Kivutar** [comment]
Ok then

**Comment by Kivutar** [comment]
http://static.kivutar.me/Lakka-RPi2.arm-devel-20161224094324-r21729-g274b40f.tar place this in your .update folder and reboot.

**Comment by CoalaJoe** [comment]
Works good on some games. I just have to asign more than 1 Core in the conifgs ;)

Thanks for the effort.

**Comment by Kivutar** [comment]
Thank you, fixed by 0adce94
