### ISSUE TITLE
UEFI Installation failed on 2 Systems (x86/x64)

### ISSUE THREAD

**Issue by shakkalakka** [lakkatv/Lakka-LibreELEC#14]
if i try to boot from usb in uefi mode there comes this message:
with 64bit release : "failed to load COM32 file vesamenu.c32"
with 32bit release : it restart before installation/booting (no message).

has try with this test-releases:
Lakka-Generic.i386-8.0-devel-20161107212249-r24214-g782622a.img
Lakka-Generic.x86_64-8.0-devel-20161203113326-r24222-g4466c01.img

images were burned with Etcher

i used on this hardware:
SHUTTLE Barebone XPC nano NC01U Celeron 3205u & Intel NUC5PPYH

In Legacy-Mode all seems to be fine with Lakka LE and its pretty usable overall!

with Lakka OE i never had a (Uefi)issue on this two machines, just runs fine there!

**Comment by Kivutar** [comment]
Ok, please try with these http://le.builds.lakka.tv/ and make a new test if you have time. It looks like the Generic images are incompatible with a lot of PCs now.
