### ISSUE TITLE
No sound with RPi3 with NOOBS

### ISSUE THREAD

**Issue by rejurime** [lakkatv/Lakka-LibreELEC#46]
Hi! 
I just try "Lakka-RPi2.arm-8.0-devel-20170206005138-r25604-g32d2949-noobs" with my Raspberry Pi 3 and I have no sound, any ideas? works fine with "Lakka-RPi2.arm-devel-20161221184910-r21729-g274b40f-noobs".
Regards.

**Comment by Kivutar** [comment]
Uncomment hdmi_drive=2 in config.txt?

**Comment by rejurime** [comment]
Still the same 😞.

**Comment by Kivutar** [comment]
Well I don't get it then, the same build runs fine on my RPi3.

**Comment by rejurime** [comment]
It's rare because I have the problem with the noobs version only.

**Comment by Kivutar** [comment]
How did you install it in noobs?

**Comment by rejurime** [comment]
I follow the steps of http://www.lakka.tv/doc/Alternative-installation-methods/ as I do with the previous version (based on OpenELEC) and that works with sound.

**Comment by Kivutar** [comment]
I could reproduce this bug. It looks like we're using a different config.txt for NOOBS. I'm going to fix it.

**Comment by Firaenix** [comment]
I have also noticed this issue when placing the .tar file in the ~/.updates/ folder and letting Lakka install the update via a reboot, I've downgraded to latest stable OpenELEC in the mean time

**Comment by Firaenix** [comment]
Just fixed it by editing the config.txt.

I added dtparam=audio=on to the bottom and now all is good.

**Comment by Kivutar** [comment]
I fixed it in the last builds.
