### ISSUE TITLE
ScummVM doesn't start

### ISSUE THREAD

**Issue by Kivutar** [lakkatv/Lakka-LibreELEC#49]
When loading from playlist.
When loading the core from Load Core.
Since the last scummvm update in Lakka.

**Comment by Ntemis** [comment]
Will fix asap

Στις 10 Φεβ 2017 14:25, ο χρήστης "Jean-André Santoni" <
notifications@github.com> έγραψε:

**Comment by Ntemis** [comment]
Fixed core now is on par with previous state, closing issue.

**Comment by Kivutar** [comment]
Thanks. I will try to update libretro-database and use scummvm files as @RobLoarch suggested
