### ISSUE TITLE
Snes9x2010 broken for netplay

### ISSUE THREAD

**Issue by Kivutar** [lakkatv/Lakka-LibreELEC#65]
This core generates 5Mo savestates!

@GregorR can you take a look at this issue please?

**Comment by GregorR** [comment]
Generating 5MB affects netplay only in its memory usage, and snes9x2010 works fine with netplay. It might have cross-architecture issues.

**Comment by Kivutar** [comment]
Aren't those savestates tranfered over the network during netplay? Or maybe it's full of zeroes and you compress them?

**Comment by GregorR** [comment]
They're compressed, and even if they weren't in a normal session it's only sent once. Netplay is not just "send savestates over and over to keep in sync"
