### ISSUE TITLE
Issues with Boxart

### ISSUE THREAD

**Issue by kryptalivian** [lakkatv/Lakka-LibreELEC#69]
I'm using a pi 3 with Lakka-RPi2.arm-8.0-devel-20170226163235-r25805-g900da08.img . 

I've found that when I point Lakka to my box art directory(**downloaded from pc and put on flash drive in own directory**) Wonderswan's, and Atari wont display box art. 

nes, snes, sega, n64, etc will grab the art work and display them.

**Comment by Kivutar** [comment]
Certainly a name mismatch for these two systems. We need to compare the names here https://github.com/libretro/libretro-database/tree/master/rdb and here http://thumbnailpacks.libretro.com/

**Comment by Kivutar** [comment]
I just tested Wonderswan Color, and I was able to see the boxart.

What Atari version?

**Comment by kryptalivian** [comment]
Loaned out flash drive that has the boxart. Closing for now.
