### ISSUE TITLE
System Freezing

### ISSUE THREAD

**Issue by kryptalivian** [lakkatv/Lakka-LibreELEC#70]
I'm running lakka on my Mac Book Pro 2015 using Lakka-Generic.x86_64-8.0-devel-20170226162544-r25805-g900da08.img 

Everytime I get to an area that pops up the on screen keyboard, the system freezes.

**Comment by DismissedGuy** [comment]
have you figured it out yet? I've got the same problem, I've got the same problem and this is the only controller I have

**Comment by DismissedGuy** [comment]
It seems to have magically fixed itself... Strange.

**Comment by kryptalivian** [comment]
Build update fixed it for me
