### ISSUE TITLE
Tp-link tl wn823n v2 not working

### ISSUE THREAD

**Issue by juri74** [lakkatv/Lakka-LibreELEC#79]
i have that wifi dongle and it isn't recognized by Lakka
@gouchi  made a test image that worked flawlessly
here the reference thread:
https://forums.libretro.com/t/tp-link-tl-wn823n-v2-support/9294/9
may be possible to add official support in future releases?
thanks

**Comment by gouchi** [comment]
It has been enabled by this [commit](https://github.com/lakkatv/Lakka-LibreELEC/commit/9810d3a0e3f75f1c493f97b00f94c28b801d9e03). Should be available in rc4 release.

Please report if it is working.

Thank you.

Kind regards,

**Comment by juri74** [comment]
thanks, i will test as soon as rc4 is released

**Comment by gouchi** [comment]
It has been [released](http://www.lakka.tv/articles/2017/03/27/lakka-20-rc4-is-out).

**Comment by juri74** [comment]
yes, my fault, i replied here BEFORE checking :D

**Comment by Kivutar** [comment]
@juri74 any news on this?

**Comment by juri74** [comment]
hello i think i have somehow damaged my odroid xu4, so i tested rc4 on a intel x64 machine with the same wi-fi dongle and it worked out of the box. so i imagine it work on odroid xu4 too

**Comment by Kivutar** [comment]
OK, thanks!
