### ISSUE TITLE
RPi3/RC4 hatari core not working

### ISSUE THREAD

**Issue by killer101** [lakkatv/Lakka-LibreELEC#88]
Hello,

I just gave the RC4 a little testing. The now available hatari core won't work for me on the RPi3. It is just doing fine using Lakka on the PC (x64).

Here's the log ...

```
RetroArch [INFO] :: This is RetroArch version 1.5.0 (Git 17235d7)
RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Mar 23 2017
RetroArch [INFO] :: Version: 1.5.0
RetroArch [INFO] :: Git: 17235d7
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "/storage/savefiles/.srm".
RetroArch [INFO] :: Redirecting savestate to "/storage/savestates/.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29970.03 Hz.
RetroArch [INFO] :: Found shader "/tmp/shaders/bilinear.glslp"
RetroArch [INFO] :: Found shader "/tmp/shaders/nearest.glslp"
RetroArch [INFO] :: Found shader "/tmp/shaders/stock.glsl"
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: Starting threaded video driver ...
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0x1.
RetroArch [INFO] :: Found GL context: videocore
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
RetroArch [INFO] :: [GL]: Version: OpenGL ES 2.0.
RetroArch [INFO] :: GL: Using resolution 1920x1080
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event0 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event0 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 384 frames
RetroArch [INFO] :: ALSA: Buffer size: 1536 frames
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
RetroArch [INFO] :: [udev]: Hotplug add: /dev/input/js0.
RetroArch [INFO] :: [udev]: Hotplug add: /dev/input/event1.
RetroArch [INFO] :: [udev]: Plugged pad: PLAYSTATION(R)3 Controller (0:0) on port #0.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event1) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event1) supports 16 force feedback effects.
RetroArch [INFO] :: Autodetect: 177 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: /tmp/joypads/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg
RetroArch [INFO] :: Using content: /storage/roms/stick/atarist/International Karate + (1988)(System 3).zip.
RetroArch [INFO] :: arg #0: retroarch
RetroArch [INFO] :: arg #1: /storage/roms/stick/atarist/International Karate + (1988)(System 3).zip
RetroArch [INFO] :: arg #2: -s
RetroArch [INFO] :: arg #3: /storage/savefiles
RetroArch [INFO] :: arg #4: -S
RetroArch [INFO] :: arg #5: /storage/savestates
RetroArch [INFO] :: arg #6: -c
RetroArch [INFO] :: arg #7: /storage/.config/retroarch/retroarch.cfg
RetroArch [INFO] :: arg #8: -L
RetroArch [INFO] :: arg #9: /tmp/cores/hatari_libretro.so
RetroArch [INFO] :: Threaded video stats: Frames pushed: 855, Frames dropped: 0.
RetroArch [INFO] :: Set config file to : /storage/.config/retroarch/retroarch.cfg
RetroArch [INFO] :: This is RetroArch version 1.5.0 (Git 17235d7)
RetroArch [INFO] :: Redirecting save file to "/storage/savefiles/International Karate + (1988)(System 3).srm".
RetroArch [INFO] :: Redirecting savestate to "/storage/savestates/International Karate + (1988)(System 3).state".
RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Mar 23 2017
RetroArch [INFO] :: Version: 1.5.0
RetroArch [INFO] :: Git: 17235d7
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading dynamic libretro core from: "/tmp/cores/hatari_libretro.so"
RetroArch [INFO] :: [overrides] no core-specific overrides found at /storage/.config/retroarch/config/Hatari/Hatari.cfg.
RetroArch [INFO] :: [overrides] no game-specific overrides found at /storage/.config/retroarch/config/Hatari/International Karate + (1988)(System 3).cfg.
RetroArch [INFO] :: Shaders: preset directory: /tmp/shaders/presets
RetroArch [INFO] :: Shaders: no game-specific preset found at /tmp/shaders/presets/Hatari/International Karate + (1988)(System 3).cgp.
RetroArch [INFO] :: Shaders: no game-specific preset found at /tmp/shaders/presets/Hatari/International Karate + (1988)(System 3).glslp.
RetroArch [INFO] :: Shaders: no core-specific preset found at /tmp/shaders/presets/Hatari/Hatari.cgp.
RetroArch [INFO] :: Shaders: no core-specific preset found at /tmp/shaders/presets/Hatari/Hatari.glslp.
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Remaps: remap directory: /storage/remappings
RetroArch [INFO] :: Remaps: no game-specific remap found at /storage/remappings/Hatari/International Karate + (1988)(System 3).rmp.
RetroArch [INFO] :: Remaps: no core-specific remap found at /storage/remappings/Hatari/Hatari.rmp.
RetroArch [INFO] :: Redirecting save file to "/storage/savefiles/International Karate + (1988)(System 3).srm".
RetroArch [INFO] :: Redirecting savestate to "/storage/savestates/International Karate + (1988)(System 3).state".
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "/storage/system".
RetroArch [INFO] :: Environ CORE_ASSETS_DIRECTORY: "/storage/roms/downloads".
Retro SYSTEM_DIRECTORY /storage/system
Retro SAVE_DIRECTORY /storage/savefiles
Retro CONTENT_DIRECTORY /storage/roms/downloads
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: RetroPad, User 1, Button "B (bottom)" => "B"
RetroArch [INFO] :: RetroPad, User 1, Button "Y (left)" => "Y"
RetroArch [INFO] :: RetroPad, User 1, Button "Select" => "Select"
RetroArch [INFO] :: RetroPad, User 1, Button "Start" => "Start"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Up" => "Up"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Down" => "Down"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Left" => "Left"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Right" => "Right"
RetroArch [INFO] :: RetroPad, User 1, Button "A (right)" => "A"
RetroArch [INFO] :: RetroPad, User 1, Button "X (up)" => "X"
RetroArch [INFO] :: RetroPad, User 1, Button "L" => "L"
RetroArch [INFO] :: RetroPad, User 1, Button "R" => "R"
RetroArch [INFO] :: RetroPad, User 1, Button "L2" => "L2"
RetroArch [INFO] :: RetroPad, User 1, Button "R2" => "R2"
RetroArch [INFO] :: RetroPad, User 1, Button "L3" => "L3"
RetroArch [INFO] :: RetroPad, User 1, Button "R3" => "R3"
RetroArch [INFO] :: Environ GET_VARIABLE Hatari_resolution:
RetroArch [INFO] :: 640x480
[libretro-test]: Got size: 640 x 480.
RetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: RetroPad, User 1, Button "Y (left)" => "Enter GUI"
RetroArch [INFO] :: RetroPad, User 1, Button "Select" => "Mouse mode toggle"
RetroArch [INFO] :: RetroPad, User 1, Button "Start" => "Keyboard overlay"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Up" => "Up"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Down" => "Down"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Left" => "Left"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Right" => "Right"
RetroArch [INFO] :: RetroPad, User 1, Button "A (right)" => "Fire"
RetroArch [INFO] :: RetroPad, User 1, Button "L" => "Joystick number"
RetroArch [INFO] :: RetroPad, User 1, Button "R" => "Mouse speed"
RetroArch [INFO] :: RetroPad, User 1, Button "L2" => "Toggle m/k status"
 0  hatari
 1  --disk-a
 2  /storage/roms/stick/atarist/International Karate + (1988)(System 3).stx
RetroConf:'/storage/system/hatari.cfg'
Hatari v1.8.0, compiled on:  Mar 26 2017, 03:47:09
Configured max Hatari resolution = 640x480, optimal for ST = 832x588
STX : STX_Insert_internal drive=0 file=/storage/roms/stick/atarist/International Karate + (1988)(System 3).stx buf=0x72027008 size=888272
Inserted disk '/storage/roms/stick/atarist/International Karate + (1988)(System 3).stx' to drive A:.
Building CPU table for configuration: 68000 (compatible mode)
NVRAM not found at '/storage/.hatari/hatari.nvram'
Bus error (core dumped)
```

**Comment by Kivutar** [comment]
Thanks for the report. It may be due to '/storage/.hatari/hatari.nvram'. Can you try to create an empty file here?

**Comment by killer101** [comment]
Nope, doesn't change anything. Except making the nvram error going away!

Here's the log ...

RetroArch [INFO] :: This is RetroArch version 1.5.0 (Git 17235d7)
RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Mar 23 2017
RetroArch [INFO] :: Version: 1.5.0
RetroArch [INFO] :: Git: 17235d7
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "/storage/savefiles/.srm".
RetroArch [INFO] :: Redirecting savestate to "/storage/savestates/.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29970.03 Hz.
RetroArch [INFO] :: Found shader "/tmp/shaders/bilinear.glslp"
RetroArch [INFO] :: Found shader "/tmp/shaders/nearest.glslp"
RetroArch [INFO] :: Found shader "/tmp/shaders/stock.glsl"
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: Starting threaded video driver ...
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0x1.
RetroArch [INFO] :: Found GL context: videocore
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
RetroArch [INFO] :: [GL]: Version: OpenGL ES 2.0.
RetroArch [INFO] :: GL: Using resolution 1920x1080
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event0 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event0 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 384 frames
RetroArch [INFO] :: ALSA: Buffer size: 1536 frames
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_music_history.lpl].
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_video_history.lpl].
RetroArch [INFO] :: Loading history file: [/storage/.config/retroarch/content_image_history.lpl].
RetroArch [INFO] :: [udev]: Hotplug add: /dev/input/js0.
RetroArch [INFO] :: [udev]: Hotplug add: /dev/input/event1.
RetroArch [INFO] :: [udev]: Plugged pad: PLAYSTATION(R)3 Controller (0:0) on port #0.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event1) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event1) supports 16 force feedback effects.
RetroArch [INFO] :: Autodetect: 177 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: /tmp/joypads/udev/Sony-PlayStation3-DualShock3-Controller-Bluetooth.cfg
RetroArch [INFO] :: Using content: /storage/roms/stick/atarist/International Karate + (1988)(System 3).zip.
RetroArch [INFO] :: arg #0: retroarch
RetroArch [INFO] :: arg #1: /storage/roms/stick/atarist/International Karate + (1988)(System 3).zip
RetroArch [INFO] :: arg #2: -s
RetroArch [INFO] :: arg #3: /storage/savefiles
RetroArch [INFO] :: arg #4: -S
RetroArch [INFO] :: arg #5: /storage/savestates
RetroArch [INFO] :: arg #6: -c
RetroArch [INFO] :: arg #7: /storage/.config/retroarch/retroarch.cfg
RetroArch [INFO] :: arg #8: -L
RetroArch [INFO] :: arg #9: /tmp/cores/hatari_libretro.so
RetroArch [INFO] :: Threaded video stats: Frames pushed: 399, Frames dropped: 0.
RetroArch [INFO] :: Set config file to : /storage/.config/retroarch/retroarch.cfg
RetroArch [INFO] :: This is RetroArch version 1.5.0 (Git 17235d7)
RetroArch [INFO] :: Redirecting save file to "/storage/savefiles/International Karate + (1988)(System 3).srm".
RetroArch [INFO] :: Redirecting savestate to "/storage/savestates/International Karate + (1988)(System 3).state".
RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Mar 23 2017
RetroArch [INFO] :: Version: 1.5.0
RetroArch [INFO] :: Git: 17235d7
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading dynamic libretro core from: "/tmp/cores/hatari_libretro.so"
RetroArch [INFO] :: [overrides] no core-specific overrides found at /storage/.config/retroarch/config/Hatari/Hatari.cfg.
RetroArch [INFO] :: [overrides] no game-specific overrides found at /storage/.config/retroarch/config/Hatari/International Karate + (1988)(System 3).cfg.
RetroArch [INFO] :: Shaders: preset directory: /tmp/shaders/presets
RetroArch [INFO] :: Shaders: no game-specific preset found at /tmp/shaders/presets/Hatari/International Karate + (1988)(System 3).cgp.
RetroArch [INFO] :: Shaders: no game-specific preset found at /tmp/shaders/presets/Hatari/International Karate + (1988)(System 3).glslp.
RetroArch [INFO] :: Shaders: no core-specific preset found at /tmp/shaders/presets/Hatari/Hatari.cgp.
RetroArch [INFO] :: Shaders: no core-specific preset found at /tmp/shaders/presets/Hatari/Hatari.glslp.
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Remaps: remap directory: /storage/remappings
RetroArch [INFO] :: Remaps: no game-specific remap found at /storage/remappings/Hatari/International Karate + (1988)(System 3).rmp.
RetroArch [INFO] :: Remaps: no core-specific remap found at /storage/remappings/Hatari/Hatari.rmp.
RetroArch [INFO] :: Redirecting save file to "/storage/savefiles/International Karate + (1988)(System 3).srm".
RetroArch [INFO] :: Redirecting savestate to "/storage/savestates/International Karate + (1988)(System 3).state".
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "/storage/system".
RetroArch [INFO] :: Environ CORE_ASSETS_DIRECTORY: "/storage/roms/downloads".
Retro SYSTEM_DIRECTORY /storage/system
Retro SAVE_DIRECTORY /storage/savefiles
Retro CONTENT_DIRECTORY /storage/roms/downloads
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: RetroPad, User 1, Button "B (bottom)" => "B"
RetroArch [INFO] :: RetroPad, User 1, Button "Y (left)" => "Y"
RetroArch [INFO] :: RetroPad, User 1, Button "Select" => "Select"
RetroArch [INFO] :: RetroPad, User 1, Button "Start" => "Start"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Up" => "Up"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Down" => "Down"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Left" => "Left"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Right" => "Right"
RetroArch [INFO] :: RetroPad, User 1, Button "A (right)" => "A"
RetroArch [INFO] :: RetroPad, User 1, Button "X (up)" => "X"
RetroArch [INFO] :: RetroPad, User 1, Button "L" => "L"
RetroArch [INFO] :: RetroPad, User 1, Button "R" => "R"
RetroArch [INFO] :: RetroPad, User 1, Button "L2" => "L2"
RetroArch [INFO] :: RetroPad, User 1, Button "R2" => "R2"
RetroArch [INFO] :: RetroPad, User 1, Button "L3" => "L3"
RetroArch [INFO] :: RetroPad, User 1, Button "R3" => "R3"
RetroArch [INFO] :: Environ GET_VARIABLE Hatari_resolution:
RetroArch [INFO] :: 640x480
[libretro-test]: Got size: 640 x 480.
RetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] :: RetroPad, User 1, Button "Y (left)" => "Enter GUI"
RetroArch [INFO] :: RetroPad, User 1, Button "Select" => "Mouse mode toggle"
RetroArch [INFO] :: RetroPad, User 1, Button "Start" => "Keyboard overlay"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Up" => "Up"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Down" => "Down"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Left" => "Left"
RetroArch [INFO] :: RetroPad, User 1, Button "D-Pad Right" => "Right"
RetroArch [INFO] :: RetroPad, User 1, Button "A (right)" => "Fire"
RetroArch [INFO] :: RetroPad, User 1, Button "L" => "Joystick number"
RetroArch [INFO] :: RetroPad, User 1, Button "R" => "Mouse speed"
RetroArch [INFO] :: RetroPad, User 1, Button "L2" => "Toggle m/k status"
 0  hatari
 1  --disk-a
 2  /storage/roms/stick/atarist/International Karate + (1988)(System 3).stx
RetroConf:'/storage/system/hatari.cfg'
Hatari v1.8.0, compiled on:  Mar 26 2017, 03:47:09
Configured max Hatari resolution = 640x480, optimal for ST = 832x588
STX : STX_Insert_internal drive=0 file=/storage/roms/stick/atarist/International Karate + (1988)(System 3).stx buf=0x74322008 size=888272
Inserted disk '/storage/roms/stick/atarist/International Karate + (1988)(System 3).stx' to drive A:.
Building CPU table for configuration: 68000 (compatible mode)
Bus error (core dumped)

**Comment by r-type** [comment]
i thinks it's libco related ,if rpi3 then arm so you should add an -marm in cflags if not the case  .

**Comment by Kivutar** [comment]
Thanks, I try it now.

**Comment by Kivutar** [comment]
@r-type is there something we can do about the location of the tos.img?
