### ISSUE TITLE
C64 (Vice) playlist symbols?

### ISSUE THREAD

**Issue by killer101** [lakkatv/Lakka-LibreELEC#92]
Hello.

Do Lakka have some? I'm just getting a black squares.

If so, what's the correct name for the playlist?

**Comment by Kivutar** [comment]
We don't have icons for the C64 yet. We don't have a database for the games either: https://github.com/libretro/libretro-database/tree/master/rdb

However, no-into does have 3 C64 databases. @RobLoach do you have free time to add them in libretro-database?

**Comment by RobLoach** [comment]
The DATs exist:
https://github.com/libretro/libretro-database/tree/master/metadat/no-intro

Just need to build the RDBs. Added an issue over at https://github.com/libretro/libretro-database/issues/432 .

As for black squares, made https://github.com/libretro/retroarch-assets/issues/131 in retroarch-assets. Feel free to close this issue. Not related to Lakka.

Thanks @killer101 + @Kivutar! Feel free to carry on discussion in those issues.

**Comment by Kivutar** [comment]
I updated the assets, we now have icons for C64.
