### ISSUE TITLE
Saturn Mednafen x86_64 Lakka 1.3.6 - CD booting problems

### ISSUE THREAD

**Issue by neosquid** [lakkatv/Lakka-LibreELEC#98]
Loading Outrun (J), results in the Saturn booting to the  CD player software interface, but not in-game (but booting the game in Windows Retroarch 1.5.0, the game boots in-game using the same, so it seems like this is not problem with the game .bin, .cue files ).

Other games have similar issues. 

I have the correct bios files in the system folder for Saturn, checked with MD5 and named correctly.

**Comment by Kivutar** [comment]
Maybe it's a case issue? Check inside your .cue that the name is correct. Windows is case insensitive, while Linux is case sensitive.

**Comment by neosquid** [comment]
Thanks, that solved the problem.
